version: 1.0.0-{build}
configuration: Release
cache: 
    - packages -> **\packages.config
before_build: nuget restore
build: 
    publish_wap: true

artifacts:

  # pushing a single file
  - path: ifcc-project.zip
